# Generated by Django 3.1 on 2020-08-22 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0008_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='user',
        ),
        migrations.AddField(
            model_name='locations',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='customUser.customuser'),
            preserve_default=False,
        ),
    ]
