# Generated by Django 3.1 on 2020-09-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0011_customuser_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
