# Generated by Django 3.1 on 2020-09-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0012_auto_20200908_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='receiver',
        ),
    ]
