# Generated by Django 3.1 on 2020-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0013_auto_20200908_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
